NAME=phonebook

CXX = c++
CXXFLAGS =-Wall -Wextra -Werror -std=c++98 -g #-g yi sil
SRC = main.cpp 
OBJS = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	c++  -o $(NAME) $(CXXFLAGS) $(OBJS) 

run: $(NAME)
	clear
	./phonebook

clean:
	rm -rf $(OBJS)
	
fclean: clean
	rm -rf $(NAME)

re: fclean all